[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "22.13.0"

[[redirects]]
  from = "/"
  to = "https://getting-started.greenwoodjs.dev"
  status = 301
  force = true