name: Continuous Integration

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install Chromium Library Dependencies
      run: |
        sh ./.github/workflows/chromium-lib-install.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.13.0
    - name: Installing project dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Build
      run: |
        yarn build