name: Continuous Integration

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [18]

    steps:
    - uses: actions/checkout@v2
    - name: Install Chromium Library Dependencies
      run: |
        sh ./.github/workflows/chromium-lib-install.sh
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Installing project dependencies
      run: |
        npm ci
    - name: Lint
      run: |
        npm run lint
    - name: Build
      run: |
        npm run build
