name: Master Integration

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Chromium Library Dependencies
      run: |
        sh ./.github/workflows/chromium-lib-install.sh
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.12.1
    - name: Installing project dependencies
      run: |
        npm ci
    - name: Build
      run: |
        npm run build